# Generated by Django 5.2.13 on 2026-04-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sender_designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
