# Generated by Django 5.2.13 on 2026-04-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campaign_sender_designation_campaign_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
