# Generated by Django 5.2.13 on 2026-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prospect_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_window_end',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_window_start',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='email',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=10),
        ),
    ]
